# based image
FROM centos
# user info
LABEL maintainer="physalily <physalily@gmail.com>"
# RUN: executed in "docker build"
RUN echo "now building..."
# CMD: executed in "docker run"
CMD echo "now running..."

